version: 2

container: &container
  working_directory: /home/pptruser/project
  docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
    - image: node:8.11-stretch
    # - image: circleci/node:8.10-browsers
#      environment:
#        TZ: Asia/Tokyo
#        TERM: xterm

jobs:

  build:
    <<: *container
    steps:
      # githubからのチェックアウト
      - checkout

      # キャッシュの読み込み：node_modules配下をキャッシュする
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v2019004201-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v2019004201-{{ .Branch }}-
            - node-v2019004201-

      # 環境構築
      - run:
          command: npm install

      # npm installでインストールされたモジュールをnode_modulesごとキャッシュ
      - save_cache:
          paths:
            - node_modules
          key: node-v2019004201-{{ .Branch }}-{{ checksum "package-lock.json" }}

  test:
    <<: *container
    steps:

      # githubからのチェックアウト
      - checkout

      # キャッシュの読み込み：node_modules配下をキャッシュする
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v2019004201-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v2019004201-{{ .Branch }}-
            - node-v2019004201-
      - run:
          command: npm test

workflows:
  version: 2
  ut-k8s-demo:
    jobs:
      - build
      - test:
        requires:
          - build
