---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-demo-sub-clusterrole1
  labels:
    app: k8s-demo-rbac
rules:
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["get"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-demo-sub-clusterrole2
  labels:
    app: k8s-demo-rbac
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-demo-clusterrole-aggregated
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        app: k8s-demo-rbac
rules:
  - apiGroups: [""]
    resources: ["pod"]
    verbs: ["get"]
