apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  labels:
    app: k8s-demo
spec:
  replicas: 3 # レプリケーションの増減数
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
        - name: k8s-demo
#          image: xxx
#          ports:
#            - containerPort: 3000
          image: nginx:1.12
          ports:
            - containerPort: 80
