apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-deploy
  labels:
    app: k8s-demo-deploy
spec:
  replicas: 3 # レプリケーションの増減数
  selector:
    matchLabels:
      app: k8s-demo-deploy
  template:
    metadata:
      labels:
        app: k8s-demo-deploy
    spec:
      containers:
        - name: www
#          image: xxx
#          ports:
#            - containerPort: 3000
          image: nginx:1.12
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
              scheme: HTTP
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            initialDelaySeconds: 3
            periodSeconds: 1
          readinessProbe:
            exec:
              command: ["ls", "/usr/share/nginx/html/50x.html"]
            timeoutSeconds: 1
            successThreshold: 2
            failureThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 3
