apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-demo-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  template:
    spec:
      containers:
        - name: sleep-container
          image: centos:6
          command: ["sleep"]
          args: ["60"]
      restartPolicy: Never